// List of categories that do not qualify an item
module.exports = [
  "Areas in Baldur's Gate",
  "Baldur's Gate games",
  "Baldur's Gate series",
  "Tanar'ri",
  '2DA',
  'Acid damage',
  'Arcane spells',
  'Areas',
  'Articles with redlinks',
  'Article stubs',
  'Attribute bonus equipment',
  'BCS',
  'Better image needed',
  'Books',
  'Bugs',
  'Bypass Magic resistance',
  'Cold damage',
  'Components',
  'Containers',
  'Creatures by alignment',
  'Creatures with immunities',
  'Creatures',
  'Crushing damage',
  'Crushing resistance',
  'Cursed items',
  'Cut content',
  'Demons',
  'Dragons',
  'Drow equipment',
  'Electricity damage',
  'Fire damage',
  'Games',
  'Game mechanics',
  'Giants',
  'Golems',
  'Image Needed',
  'Image needed',
  'Immune to magical weapons',
  'Immune to normal weapons',
  'Immune to +1',
  'Immune to +2',
  'Immune to +3',
  'Imps (class)',
  'Infobox Incomplete',
  'Infobox incomplete',
  'Infobox upgrade',
  'Innate abilities',
  'Items in BG II: EE: SoA',
  'Items in BG II: EE: ToB',
  'Items in BG II: SoA',
  'Items in BG II: ToB',
  'Items in BG',
  'Items in BG: EE',
  'Items in BG: SoD',
  'Items in BG: TotSC',
  'Items needed in quests and dialogues',
  'Items of Balduran',
  'Items',
  'Item description images',
  'Item icons',
  'Keys',
  'Liches',
  'Lists',
  'Long swords (creature)',
  'Magical damage',
  'Magical weapons',
  'Merchants',
  'Minotaurs',
  'Miscellaneous items',
  'Missile avoidance',
  'Missile damage',
  'Mods',
  'Mod elements',
  'New items in BG II: EE: SoA',
  'New items in BG II: ToB',
  'New items in BG II: ToB‎',
  'New items in BG: EE',
  'New items in BG: SoD',
  'New items in BG: TotSC',
  'Non-enchanted items',
  'Non-enchanted weapons',
  'Normal weapons',
  'Ogres (race)',
  'Overpowered elements',
  'Pages with links to the Forgotten Realms Wiki',
  'Piercing damage',
  'Piercing resistance',
  'Poison damage',
  'Prone to fire',
  'Quests',
  'Quest items',
  'Random treasure',
  'Ranged weapons with unlimited ammunition',
  'Restoration mods',
  'Scrolls',
  'Slashing damage',
  'Slashing resistance',
  'Smiths',
  'Spells by level',
  'Spells',
  'Stores',
  'Storyline',
  'Temples',
  'Tomes',
  'Trolls',
  'Undead',
  'Verification needed',
  'Wizard spells by level',
  'Wizard spells of level 1',
  'Wizard spells of level 2',
  'Wizard spells of level 3',
  ' Body Armor',
  '+1 weapons',
  '+2 weapons',
  '+4 weapons',
  '+6 items',
  '+6 weapons',
];
