module.exports = [
  'Arrow',
  'Arrow +1',
  'Arrow +2',
  'Arrow +3',
  'Backwhacker +2',
  'Bag of Plenty',
  'Bastard Sword +1',
  "Durlag's Pride",
  "Koveras's Ring of Protection",
  'Bastard Sword +2',
  'Bastard Sword +3',
  'Battle Axe +2',
  'Battle Axe +3',
  'Big Metal Unit',
  'Blade of the Equalizer',
  'Bolt +1',
  'Bolt +3',
  'Buckler +1 (Skeleton shield)',
  'Buckler +1',
  'Bullet +1',
  'Bullet +2',
  'Bullet +3',
  'Bullet +4',
  'Chain Mail +2',
  'Cloak of Protection +1',
  'Club +1',
  'Club +3',
  'Club',
  'Composite Longbow +1',
  'Composite Longbow +2',
  'Composite Longbow +3',
  'Composite Longbow',
  'Cursed Scroll of Foolishness',
  'Cursed Scroll of Petrification',
  'Cursed Scroll of Summon Monster',
  'Cursed Scroll of Ugliness',
  'Dagger +1',
  'Dagger +2',
  'Dagger +3',
  'Dagger',
  'Elven Chain +1',
  'Firetooth (crossbow)', // There are two Firetooth items. It created collision in slugs, so the easiest way was to remove one
  'Flail +1',
  'Flail +2',
  'Flail +3',
  'Full Plate Armor +1',
  'Full Plate Mail +2',
  'Gesen Bow String',
  'Ghost Locket',
  'Golden Pantaloons',
  'Halberd +1',
  'Halberd +2',
  'Halberd +3',
  'Heavy Crossbow +1',
  'Heavy Crossbow +2',
  'Heavy Crossbow +3',
  'Hide Armor +1',
  'Hilt of the Equalizer',
  'House Catanzaro Insignia',
  'House Ryrrl Insignia',
  'Katana +1',
  'Katana +2',
  'Katana +3',
  'Katana',
  'Large Shield +2',
  'Leather Armor +1',
  'Leather Armor +2',
  'Leather Armor +3',
  'Light Crossbow +1',
  'Light Crossbow +2',
  'Light Crossbow +3',
  'Light Crossbow',
  'Lock of Hair from Kirinhale',
  'Longbow +1',
  'Longbow +2',
  'Longbow +3',
  'Long Sword +1',
  'Long Sword +2',
  'Long Sword +3',
  'Mace +2',
  'Mace +3',
  'Medium Shield +2',
  'Mithral Chain Mail',
  'Morning Star +1',
  'Morning Star +2',
  'Morning Star +3',
  'Ninjatō +1',
  'Ninjatō +2',
  'Plate Mail +1',
  'Pommel Jewel of the Equalizer',
  'Portal Key',
  'Protection From Acid (protection scroll)',
  'Protection From Cold (protection scroll)',
  'Protection From Electricity (protection scroll)',
  'Protection From Poison',
  'Quarterstaff +1',
  'Quarterstaff +2',
  'Red Potion',
  'Rune of Clangeddin',
  'Scimitar +1',
  'Scimitar +3',
  'Shortbow +1',
  'Shortbow +2',
  'Shortbow +3',
  'Short Sword +1',
  'Short Sword +2',
  'Short Sword +3',
  'Sling +1',
  'Sling +2',
  'Sling +3',
  'Sling',
  'Small Shield +2',
  'Spear +2',
  'Spear +3',
  'Splint Mail +1',
  'Stone to Flesh Scroll',
  'Studded Leather Armor +1',
  'Throwing Axe +1',
  'Throwing Axe +2',
  'Throwing Dagger +1',
  'Tome of Clear Thought',
  'Two-handed Sword +1',
  'Two-handed Sword +2',
  'Two-handed Sword +3',
  'Wakizashi +1',
  'War Hammer +1',
  'War Hammer +2',
  'War Hammer +3',
  'Wave Blade',
  'Wave Shaft',
];
